<a href="https://colab.research.google.com/github/Abhrar69/Python/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Numpy Assignment***

In [2]:
import pandas as pd
import numpy as np

In [3]:
arr = np.array(range(1,21))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [4]:
arr + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25])

In [5]:
arr - 5

array([-4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
       13, 14, 15])

In [6]:
arr * 5

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [7]:
arr / 5

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6,
       2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. ])

In [8]:
np.sum(arr)

210

In [9]:
np.mean(arr)

10.5

In [10]:
np.max(arr)

20

In [11]:
np.min(arr)

1

In [12]:
arr = np.random.randint(10,50,(4,5))
arr

array([[44, 21, 35, 46, 47],
       [23, 40, 11, 39, 28],
       [29, 18, 44, 25, 19],
       [12, 41, 42, 31, 30]])

In [13]:
arr[:,3]

array([46, 39, 25, 31])

In [14]:
arr[:2,:]

array([[44, 21, 35, 46, 47],
       [23, 40, 11, 39, 28]])

In [15]:
arr[arr > 25] = 100
arr

array([[100,  21, 100, 100, 100],
       [ 23, 100,  11, 100, 100],
       [100,  18, 100,  25,  19],
       [ 12, 100, 100, 100, 100]])

In [16]:
arr = np.arange(1,13)
arr = arr.reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [18]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [19]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
arr1 = np.array([[1],[2],[3]])
arr2 = np.array([[4,5,6,7]])
print(arr1)
print(arr2)

[[1]
 [2]
 [3]]
[[4 5 6 7]]


In [22]:
arr1 + arr2

array([[ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10]])

In [24]:
arr = np.random.random((3,3))
arr

array([[0.42894126, 0.9509158 , 0.39372812],
       [0.22021261, 0.22394658, 0.39333443],
       [0.17915187, 0.70448694, 0.63236458]])

In [27]:
arr.mean()

0.4585646892734629

In [28]:
arr.std()

0.24320978223543185

In [29]:
arr.var()

0.05915099817500618

In [32]:
np.median(arr,axis=1)

array([0.42894126, 0.22394658, 0.63236458])

In [33]:
np.median(arr,axis=0)

array([0.22021261, 0.70448694, 0.39372812])

In [38]:
arr = np.random.randint(50,100,15)
arr

array([84, 62, 51, 55, 74, 65, 61, 57, 89, 97, 84, 75, 95, 96, 92])

In [39]:
np.sort(arr)

array([51, 55, 57, 61, 62, 65, 74, 75, 84, 84, 89, 92, 95, 96, 97])

In [42]:
np.where(arr > 75)

(array([ 0,  8,  9, 10, 12, 13, 14]),)

In [45]:
arr1 = np.random.randint(1, 10, (3, 3))
arr2 = np.random.randint(11, 20, (3, 3))

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

Array 1:
 [[4 4 4]
 [2 1 2]
 [6 5 6]]
Array 2:
 [[17 19 14]
 [11 13 14]
 [14 19 16]]


In [46]:
arr1 + arr2

array([[21, 23, 18],
       [13, 14, 16],
       [20, 24, 22]])

In [47]:
arr1 - arr2

array([[-13, -15, -10],
       [ -9, -12, -12],
       [ -8, -14, -10]])

In [48]:
arr1 * arr2

array([[68, 76, 56],
       [22, 13, 28],
       [84, 95, 96]])

In [49]:
arr1 / arr2

array([[0.23529412, 0.21052632, 0.28571429],
       [0.18181818, 0.07692308, 0.14285714],
       [0.42857143, 0.26315789, 0.375     ]])

In [50]:
np.dot(arr1, arr2)

array([[168, 204, 176],
       [ 73,  89,  74],
       [241, 293, 250]])